apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: location-listener-v3
  labels:
    app: listener-v3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: listener-v3
  template:
    metadata:
      labels:
        app: listener-v3
    spec:
      containers:
      - name: listener-v3
        image: localhost:5000/location-listener:v3
        ports:
        - containerPort: 12345
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: listener-service-v3
  namespace: location-listener-v3
spec:
  selector:
    app: listener-v3
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
  sessionAffinity: ClientIP

