apiVersion: v1
kind: ConfigMap
metadata:
  name: ngrok-configmap
  namespace: location-listener-v3
data:
  ngrok.yml: |
    version: "2"
    authtoken: 2dDkCLHA5sPabHgB1EwIcMrp1R8_5PBrt1EEvyEQ5kWcsRSwL
    tunnels:
      location:
        proto: tcp
        addr: listener-service-v3.location-listener-v3:12345